name: iOS CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Xcode
        run: sudo xcode-select --install

      - name: Accept Xcode license
        run: sudo xcodebuild -license accept

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install dependencies
        run: |
          xcodebuild -resolvePackageDependencies
          pod install

      - name: Build
        run: xcodebuild -project SwiftUI/CryptoTracker/CryptoTracker.xcodeproj -scheme CryptoTracker -destination 'platform=iOS Simulator,name=iPhone 15' build
